# src/main/resources/application.yml

kakaopay:
  host: https://open-api.kakaopay.com
  secret-key: ${KAKAOPAY_SECRET_KEY}     # Render env (dev key)
  cid: TC0ONETIME
  ready-path: /online/v1/payment/ready
  approve-path: /online/v1/payment/approve

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  front-base-url: ${FRONT_BASE_URL:http://localhost:3000}
